/* Generated by scripts/generate-design-tokens.mjs from tokens/motion.json. Do not edit. */
export const DUR = {
  "instant": 90,
  "fast": 160,
  "base": 240,
  "slow": 340,
  "view": 480,
  "immersive": 560,
  "ambient": 800,
  "brand": 720
} as const;

export const EASE = {
  "out": "cubic-bezier(0.16, 1, 0.30, 1)",
  "in": "cubic-bezier(0.50, 0, 0.85, 0)",
  "inout": "cubic-bezier(0.65, 0, 0.35, 1)",
  "emphasis": "cubic-bezier(0.20, 0, 0, 1)",
  "spring": "cubic-bezier(0.34, 1.35, 0.64, 1)"
} as const;
export const EXIT_RATIO = 0.7;
export const STAGGER_STEP_MS = 20;
export const STAGGER_MAX_ITEMS = 6;
export const IDLE_HIDE_MS = 3000;
export const DANMAKU_SPEED_PX_S = 168;
export const DANMAKU_LANE_GAP_PX = 48;
